# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
        
    - name: Install Typescript
      run: npm install -g typescript
  
    - name: Build
      run: tsc
